<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="01HW1045896" name="bsiShopRedesignSprint2.CheckWarningMsgAddtoBasket" tests="1" failures="0" timestamp="11 Apr 2018 16:36:50 GMT" time="51.857" errors="1">
  <testcase name="checkWarningMsgPDF" time="51.857" classname="bsiShopRedesignSprint2.CheckWarningMsgAddtoBasket">
    <error type="java.lang.AssertionError" message="Adding same Product to Basket and checking warning message was unsuccessful">
      <![CDATA[java.lang.AssertionError: Adding same Product to Basket and checking warning message was unsuccessful
	at org.testng.Assert.fail(Assert.java:94)
	at utilities.CommonHelper.reportFailure(CommonHelper.java:66)
	at bsiShopRedesignSprint2.CheckWarningMsgAddtoBasket.checkWarningMsgPDF(CheckWarningMsgAddtoBasket.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- checkWarningMsgPDF -->
</testsuite> <!-- bsiShopRedesignSprint2.CheckWarningMsgAddtoBasket -->
